# COLOURS
autoload -Uz colors && colors	

# OPTIONS
stty stop undef		# Disable ctrl-s to freeze terminal.
setopt interactive_comments

# PROMPT
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats 'on %F{magenta} %b%f'
setopt prompt_subst
NEWLINE=$'\n' # New line shortcut
PROMPT='${NEWLINE}%B%F{cyan}%~%f%b %B${vcs_info_msg_0_}%b${NEWLINE}%B%(?.%F{green}.%F{red})➜ %f%b '
RPROMPT="%n@%m [%*]"

# VI MODE
bindkey -v
export KEYTIMEOUT=1
# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -v '^?' backward-delete-char
# Change cursor shape for different vi modes.
function zle-keymap-select () {
    case $KEYMAP in
        vicmd) echo -ne '\e[1 q';;      # block
        viins|main) echo -ne '\e[5 q';; # beam
    esac
}
zle -N zle-keymap-select
zle-line-init() {
    zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
    echo -ne "\e[5 q"
}
zle -N zle-line-init
echo -ne '\e[5 q' # Use beam shape cursor on startup.
preexec() { echo -ne '\e[5 q' ;} # Use beam shape cursor for each new prompt.
# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line
bindkey -M vicmd '^[[P' vi-delete-char
bindkey -M vicmd '^e' edit-command-line
bindkey -M visual '^[[P' vi-delete
bindkey -M viins '^R' fzf-history-widget
bindkey -M vicmd '^R' fzf-history-widget

# tat: tmux attach
function tat {
  # gets the name of the current directory and removes periods, which tmux doesn’t like.
  name=$(basename `pwd` | sed -e 's/\.//g')

  if tmux ls 2>&1 | grep "$name"; then
    # if any session with the same name is open, it re-attaches to it.
    tmux attach -t "$name"
  elif [ -f .envrc ]; then
    # otherwise, it checks if an .envrc file is present and starts a new tmux session using direnv exec.
    direnv exec / tmux new-session -s "$name"
  else
    # otherwise, starts a new tmux session with that name.
    tmux new-session -s "$name"
  fi
}

eval $(/opt/homebrew/bin/brew shellenv)

# globalias: expand global aliases when space is pressed
# from https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/globalias/globalias.plugin.zsh
globalias() {
  # Get last word to the left of the cursor:
  # (z) splits into words using shell parsing
  # (A) makes it an array even if there's only one element
  local word=${${(Az)LBUFFER}[-1]}
  if [[ $GLOBALIAS_FILTER_VALUES[(Ie)$word] -eq 0 ]]; then
    zle _expand_alias
    zle expand-word
  fi
  zle self-insert
}
zle -N globalias

# space expands all aliases, including global
bindkey -M emacs " " globalias
bindkey -M viins " " globalias

# control-space to make a normal space
bindkey -M emacs "^ " magic-space
bindkey -M viins "^ " magic-space

# normal space during searches
bindkey -M isearch " " magic-space

# 1password-cli plugins
source ~/.config/op/plugins.sh

# workspace CLI: init ws() after direnv sets WORKSPACE_CLI_ACTIVE
_workspace_cli_init() {
  if [[ -n "$WORKSPACE_CLI_ACTIVE" && -z "${functions[ws]}" ]]; then
    eval "$(workspace shell-init zsh)"
  fi
}
precmd_functions+=(_workspace_cli_init)
